### ISSUE TITLE
How to add a new alert for Split Brain in my postgresql cluster.

### ISSUE THREAD

**Issue by sb1975** [wrouesnel/postgres_exporter#371] opened 2020-02-12 20:42 UTC
As a Ops User I want to get an alert if there is a Split-Brain scenario and more than one postgresql database  is in primary mode.

Can anyone walk through the steps, in which files and what changes would need to be done to enable that please.

**Comment by wrouesnel** [comment] 2020-02-25 13:50
This is a usage issue not a bug report. Closing.

**Closed by wrouesnel** 2020-02-25 13:50 UTC
